version: "2"

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./volumes/proxy/certs:/etc/nginx/certs:ro"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    networks:
      - proxy-tier


  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./volumes/proxy/certs:/etc/nginx/certs:rw"
    environment:
      - ACME_CA_URI=https://acme-staging.api.letsencrypt.org/directory

  #simple-site:
  #  image: nginx
  #  container_name: simple-site
  #  volumes:
  #    - "../../../volumes/examples/simple-site/conf.d/:/etc/nginx/conf.d"
  #  environment:
  #    - VIRTUAL_HOST=site.example.com
  #    - VIRTUAL_NETWORK=nginx-proxy
  #    - VIRTUAL_PORT=80
  #    - LETSENCRYPT_HOST=site.example.com
  #    - LETSENCRYPT_EMAIL=email@example.com
  #  networks:
  #    - proxy-tier

networks:
  proxy-tier:
    external:
      name: nginx-proxy
