version: '2'
services:
  app:
    build: .
    environment:
      - PORT=80
      - NODE_ENV=production

      - SEED=true

      - MYSQL_USER=mfpum-user
      - MYSQL_PASSWORD=mfpum-password
      - MYSQL_DATABASE=mfpum
      - MYSQL_HOST=db

      - VIRTUAL_HOST=mfpum.jcirizar.com
      - VIRTUAL_PORT=80
      - VIRTUAL_NETWORK=nginx-proxy
      - LETSENCRYPT_HOST=mfpum.jcirizar.com
      - LETSENCRYPT_EMAIL=developer@jcirizar.com
    ports:
      - "80"
    restart: always
    depends_on:
      - db
    networks:
      - proxy-tier
      - back

  db:
    image: mysql:5
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root-password
      - MYSQL_DATABASE=mfpum
      - MYSQL_USER=mfpum-user
      - MYSQL_PASSWORD=mfpum-password
    networks:
      - back

  db-seed:
    build: db-seed
    environment:
      - MYSQL_USER=mfpum-user
      - MYSQL_PASSWORD=mfpum-password
      - MYSQL_HOST=db
    depends_on:
      - db
    networks:
      - back

networks:
  proxy-tier:
    external:
       name: nginx-proxy
  back:
    driver: bridge
